apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup
  labels:
    app: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
  template:
    metadata:
      labels:
        app: backup
    spec:
      containers:
      - name: backup
        image: ghcr.io/hungluong05/tickethub-backup:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            ephemeral-storage: "300Mi"
        env:
          - name: POSTGRES_USER
            value: hld
          - name: POSTGRES_PASSWORD
            value: secretpassword
          - name: POSTGRES_DB
            value: eventdb
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_HOST
            value: eventdb
      imagePullSecrets:
      - name: ghcr-secret
          
        