apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ticket-kafka
  labels:
    app: kafka
spec:
  kafka:
    version: 3.9.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      # offsets.topic.replication.factor: 3
      # transaction.state.log.replication.factor: 3
      # transaction.state.log.min.isr: 2
      # default.replication.factor: 3
      # min.insync.replicas: 2
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.3"
    storage:
      type: ephemeral
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 60
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 60
  zookeeper:
    replicas: 1
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 60
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 60
    storage:
      type: ephemeral
  # entityOperator:
  #   topicOperator: {}
  #   userOperator: {}
  #   livenessProbe:
  #     initialDelaySeconds: 30
  #     timeoutSeconds: 30
  #   readinessProbe:
  #     initialDelaySeconds: 30
  #     timeoutSeconds: 30