apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        include mime.types;

        server {
            listen 80;
            server_name _;

            location / {
                return 200 "Welcome to TicketHub";
            }

            location = /api/auth/login {
                proxy_pass http://auth:8000/login;
            }

            location = /api/auth/register {
                proxy_pass http://auth:8000/register;
            }

            location = api/auth/verify {
                internal;
                proxy_pass http://auth:8000/verify;
                proxy_set_header X-Original-URI $request_uri;
                proxy_set_header Content-Length "";
                proxy_pass_request_body off;
                proxy_set_header X-User-ID $upstream_http_user_id;
            }

            location /api/ {
                
            }

            # location /api/event {
            #     auth_request /verify;
            #     auth_request_set $user_id $upstream_http_x_user_id;
            #     error_page 401 = @error401;
            #     error_page 403 = @error403;
            #     proxy_set_header X-User-ID $user_id;
            #     proxy_pass http://tickethub-event:8001/api/event;
            # }

            location @error401 {
                return 401 "Unauthorized";
            }

            location @error403 {
                return 403 "Forbidden";
            }
        }
    }