apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-eventdb
  labels:
    app: redis-eventdb
spec:
  selector:
    matchLabels:
      app: redis-eventdb
  template:
    metadata:
      labels:
        app: redis-eventdb
    spec:
      containers:
      - name: redis
        image: redis:7.4.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          value: secretpassword
      volumes:
      - name: redis-eventdb-persistent-storage
        persistentVolumeClaim:
          claimName: redis-event-data-pvc
