apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
  labels:
    app: userdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
      - name: userdb
        image: postgres:13
        ports:
        - containerPort: 5432
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        #     storage: "2Gi"
        env:
        - name: POSTGRES_USER
          value: hld
        - name: POSTGRES_PASSWORD
          value: secretpassword
        - name: POSTGRES_DB
          value: userdb
        volumeMounts:
        - name: userdb-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: userdb-persistent-storage
        persistentVolumeClaim:
          claimName: user-data-pvc
