// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: event_perm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventPerm_AddEventPerm_FullMethodName    = "/proto.EventPerm/AddEventPerm"
	EventPerm_DeleteEventPerm_FullMethodName = "/proto.EventPerm/DeleteEventPerm"
)

// EventPermClient is the client API for EventPerm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventPermClient interface {
	AddEventPerm(ctx context.Context, in *AddEventPermRequest, opts ...grpc.CallOption) (*AddEventPermResponse, error)
	DeleteEventPerm(ctx context.Context, in *DeleteEventPermRequest, opts ...grpc.CallOption) (*DeleteEventPermResponse, error)
}

type eventPermClient struct {
	cc grpc.ClientConnInterface
}

func NewEventPermClient(cc grpc.ClientConnInterface) EventPermClient {
	return &eventPermClient{cc}
}

func (c *eventPermClient) AddEventPerm(ctx context.Context, in *AddEventPermRequest, opts ...grpc.CallOption) (*AddEventPermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEventPermResponse)
	err := c.cc.Invoke(ctx, EventPerm_AddEventPerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventPermClient) DeleteEventPerm(ctx context.Context, in *DeleteEventPermRequest, opts ...grpc.CallOption) (*DeleteEventPermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEventPermResponse)
	err := c.cc.Invoke(ctx, EventPerm_DeleteEventPerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventPermServer is the server API for EventPerm service.
// All implementations must embed UnimplementedEventPermServer
// for forward compatibility.
type EventPermServer interface {
	AddEventPerm(context.Context, *AddEventPermRequest) (*AddEventPermResponse, error)
	DeleteEventPerm(context.Context, *DeleteEventPermRequest) (*DeleteEventPermResponse, error)
	mustEmbedUnimplementedEventPermServer()
}

// UnimplementedEventPermServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventPermServer struct{}

func (UnimplementedEventPermServer) AddEventPerm(context.Context, *AddEventPermRequest) (*AddEventPermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEventPerm not implemented")
}
func (UnimplementedEventPermServer) DeleteEventPerm(context.Context, *DeleteEventPermRequest) (*DeleteEventPermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEventPerm not implemented")
}
func (UnimplementedEventPermServer) mustEmbedUnimplementedEventPermServer() {}
func (UnimplementedEventPermServer) testEmbeddedByValue()                   {}

// UnsafeEventPermServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventPermServer will
// result in compilation errors.
type UnsafeEventPermServer interface {
	mustEmbedUnimplementedEventPermServer()
}

func RegisterEventPermServer(s grpc.ServiceRegistrar, srv EventPermServer) {
	// If the following call pancis, it indicates UnimplementedEventPermServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventPerm_ServiceDesc, srv)
}

func _EventPerm_AddEventPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEventPermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventPermServer).AddEventPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventPerm_AddEventPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventPermServer).AddEventPerm(ctx, req.(*AddEventPermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventPerm_DeleteEventPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventPermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventPermServer).DeleteEventPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventPerm_DeleteEventPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventPermServer).DeleteEventPerm(ctx, req.(*DeleteEventPermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventPerm_ServiceDesc is the grpc.ServiceDesc for EventPerm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventPerm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventPerm",
	HandlerType: (*EventPermServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEventPerm",
			Handler:    _EventPerm_AddEventPerm_Handler,
		},
		{
			MethodName: "DeleteEventPerm",
			Handler:    _EventPerm_DeleteEventPerm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event_perm.proto",
}
