name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME_AUTH: ${{ github.repository }}-auth
  IMAGE_NAME_EVENT: ${{ github.repository }}-event
  IMAGE_NAME_TICKET: ${{ github.repository }}-ticket
  IMAGE_NAME_BACKUP: ${{ github.repository }}-backup


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build, push, and sign container Auth
      - name: Extract Docker metadata
        id: meta-auth
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AUTH }}
          
      - name: Build and push Docker image
        id: build-and-push-auth
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./auth
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-auth.outputs.tags }}
          labels: ${{ steps.meta-auth.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-auth.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-auth.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
      
      # Build, push, and sign container Event
      - name: Extract Docker metadata
        id: meta-event
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_EVENT }}
          
      - name: Build and push Docker image
        id: build-and-push-event
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./event
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-event.outputs.tags }}
          labels: ${{ steps.meta-event.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-event.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-event.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # Build, push, and sign container Ticket
      - name: Extract Docker metadata
        id: meta-ticket
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_TICKET }}
          
      - name: Build and push Docker image
        id: build-and-push-ticket
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./ticket
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-ticket.outputs.tags }}
          labels: ${{ steps.meta-ticket.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-ticket.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-ticket.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
      
      # Build, push, and sign container Backup
      - name: Extract Docker metadata
        id: meta-backup
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKUP }}
      
      - name: Build and push Docker image
        id: build-and-push-backup
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./backup
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backup.outputs.tags }}
          labels: ${{ steps.meta-backup.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-backup.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-backup.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      
